const { sequelize } = require("./src/config/database");
const College = require("./src/models/College");
const Course = require("./src/models/Course");
const Placement = require("./src/models/Placement");
const Cutoff = require("./src/models/Cutoff");

const top20Colleges = [
  {
    name: "Indian Institute of Technology Madras",
    location: "Chennai",
    state: "Tamil Nadu",
    rating: 4.9,
    college_type: "government",
    established_year: 1959,
    affiliation: "Autonomous",
    naac_grade: "A++",
    nirf_rank: 1,
    total_intake: 1300,
    website: "https://www.iitm.ac.in",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/6/69/IIT_Madras_Logo.svg/1200px-IIT_Madras_Logo.svg.png",
    overview: "IIT Madras is consistently ranked #1 in NIRF. It is known for its sprawling campus, strong research output, and exceptional placement statistics.",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 850000, fees_per_year: 212500, degree_type: "UG", specialisation: "Computer Science", seats_available: 87 }],
    placements: [{ year: 2024, average_ctc: 21.48, median_ctc: 18.0, highest_ctc: 131.0, placement_percentage: 85, top_recruiters: "Microsoft, Texas Instruments, Bajaj Auto", total_offers: 1044 }],
    cutoffs: [{ exam_name: "JEE Advanced", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 148, year: 2024, round: 6 }]
  },
  {
    name: "Indian Institute of Technology Delhi",
    location: "New Delhi",
    state: "Delhi",
    rating: 4.8,
    college_type: "government",
    established_year: 1961,
    affiliation: "Autonomous",
    naac_grade: "A++",
    nirf_rank: 2,
    total_intake: 1200,
    website: "https://home.iitd.ac.in",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fd/Indian_Institute_of_Technology_Delhi_Logo.svg/1200px-Indian_Institute_of_Technology_Delhi_Logo.svg.png",
    overview: "IIT Delhi offers cutting-edge engineering programs and has a vibrant entrepreneurial ecosystem in the heart of the national capital.",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 850000, fees_per_year: 212500, degree_type: "UG", specialisation: "Computer Science", seats_available: 99 }],
    placements: [{ year: 2024, average_ctc: 20.5, median_ctc: 18.5, highest_ctc: 240.0, placement_percentage: 84, top_recruiters: "Jane Street, Optiver, Google", total_offers: 1050 }],
    cutoffs: [{ exam_name: "JEE Advanced", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 116, year: 2024, round: 6 }]
  },
  {
    name: "Indian Institute of Technology Kanpur",
    location: "Kanpur",
    state: "Uttar Pradesh",
    rating: 4.8,
    college_type: "government",
    established_year: 1959,
    affiliation: "Autonomous",
    naac_grade: "A++",
    nirf_rank: 4,
    total_intake: 1100,
    website: "https://www.iitk.ac.in",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a3/IIT_Kanpur_Logo.svg/1200px-IIT_Kanpur_Logo.svg.png",
    overview: "IIT Kanpur is renowned for its rigorous academics and strong emphasis on research and development in engineering and sciences.",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 850000, fees_per_year: 212500, degree_type: "UG", specialisation: "Computer Science", seats_available: 114 }],
    placements: [{ year: 2024, average_ctc: 22.0, median_ctc: 19.0, highest_ctc: 190.0, placement_percentage: 85, top_recruiters: "Tower Research, Google, Microsoft", total_offers: 989 }],
    cutoffs: [{ exam_name: "JEE Advanced", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 248, year: 2024, round: 6 }]
  },
  {
    name: "Indian Institute of Technology Kharagpur",
    location: "Kharagpur",
    state: "West Bengal",
    rating: 4.7,
    college_type: "government",
    established_year: 1951,
    affiliation: "Autonomous",
    naac_grade: "A++",
    nirf_rank: 6,
    total_intake: 1500,
    website: "https://www.iitkgp.ac.in",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/1/1c/IIT_Kharagpur_Logo.svg/1200px-IIT_Kharagpur_Logo.svg.png",
    overview: "The oldest IIT, IIT Kharagpur has the largest campus and offers a diverse range of undergraduate and postgraduate programs.",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 850000, fees_per_year: 212500, degree_type: "UG", specialisation: "Computer Science", seats_available: 80 }],
    placements: [{ year: 2024, average_ctc: 19.5, median_ctc: 17.0, highest_ctc: 260.0, placement_percentage: 80, top_recruiters: "Apple, Google, Microsoft", total_offers: 1300 }],
    cutoffs: [{ exam_name: "JEE Advanced", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 279, year: 2024, round: 6 }]
  },
  {
    name: "Birla Institute of Technology and Science",
    location: "Pilani",
    state: "Rajasthan",
    rating: 4.8,
    college_type: "private",
    established_year: 1964,
    affiliation: "Deemed University",
    naac_grade: "A++",
    nirf_rank: 20,
    total_intake: 1000,
    website: "https://www.bits-pilani.ac.in",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/BITS_Pilani-Logo.svg/1200px-BITS_Pilani-Logo.svg.png",
    overview: "BITS Pilani is India's premier private engineering institute, known for its zero-attendance policy and stellar alumni network.",
    courses: [{ name: "B.E. Computer Science", duration: "4 Years", fees: 2400000, fees_per_year: 600000, degree_type: "UG", specialisation: "Computer Science", seats_available: 120 }],
    placements: [{ year: 2024, average_ctc: 24.0, median_ctc: 18.0, highest_ctc: 60.0, placement_percentage: 92, top_recruiters: "Google, Amazon, Microsoft, Uber", total_offers: 1100 }],
    cutoffs: [{ exam_name: "BITSAT", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 331, year: 2024, round: 1 }]
  },
  {
    name: "National Institute of Technology Trichy",
    location: "Tiruchirappalli",
    state: "Tamil Nadu",
    rating: 4.7,
    college_type: "government",
    established_year: 1964,
    affiliation: "Autonomous",
    naac_grade: "A++",
    nirf_rank: 9,
    total_intake: 1000,
    website: "https://www.nitt.edu",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/8/87/NIT_Trichy_logo.svg/1200px-NIT_Trichy_logo.svg.png",
    overview: "NIT Trichy is the top-ranked NIT in India, providing excellent engineering education and consistently high placements.",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 500000, fees_per_year: 125000, degree_type: "UG", specialisation: "Computer Science", seats_available: 119 }],
    placements: [{ year: 2024, average_ctc: 15.5, median_ctc: 12.0, highest_ctc: 52.0, placement_percentage: 90, top_recruiters: "Amazon, Morgan Stanley, Oracle", total_offers: 900 }],
    cutoffs: [{ exam_name: "JEE Main", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 1147, year: 2024, round: 6 }]
  },
  {
    name: "National Institute of Technology Karnataka",
    location: "Surathkal",
    state: "Karnataka",
    rating: 4.6,
    college_type: "government",
    established_year: 1960,
    affiliation: "Autonomous",
    naac_grade: "A++",
    nirf_rank: 12,
    total_intake: 900,
    website: "https://www.nitk.ac.in",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/NITK_Surathkal_Logo.svg/1200px-NITK_Surathkal_Logo.svg.png",
    overview: "NITK Surathkal boasts a beautiful private beach campus and is highly sought after for its strong engineering programs.",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 500000, fees_per_year: 125000, degree_type: "UG", specialisation: "Computer Science", seats_available: 116 }],
    placements: [{ year: 2024, average_ctc: 15.0, median_ctc: 11.5, highest_ctc: 54.0, placement_percentage: 88, top_recruiters: "Microsoft, Uber, Amazon", total_offers: 850 }],
    cutoffs: [{ exam_name: "JEE Main", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 1984, year: 2024, round: 6 }]
  },
  {
    name: "Delhi Technological University",
    location: "New Delhi",
    state: "Delhi",
    rating: 4.5,
    college_type: "government",
    established_year: 1941,
    affiliation: "Autonomous",
    naac_grade: "A++",
    nirf_rank: 29,
    total_intake: 2000,
    website: "https://dtu.ac.in",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b5/DTU%2C_Delhi_official_logo.png/220px-DTU%2C_Delhi_official_logo.png",
    overview: "Formerly DCE, DTU is a premier engineering university in Delhi known for strong industry ties and massive placement figures.",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 800000, fees_per_year: 200000, degree_type: "UG", specialisation: "Computer Science", seats_available: 480 }],
    placements: [{ year: 2024, average_ctc: 15.2, median_ctc: 11.0, highest_ctc: 64.0, placement_percentage: 85, top_recruiters: "Google, Amazon, Microsoft, Adobe", total_offers: 1600 }],
    cutoffs: [{ exam_name: "JEE Main", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 4876, year: 2024, round: 5 }]
  },
  {
    name: "Jadavpur University",
    location: "Kolkata",
    state: "West Bengal",
    rating: 4.7,
    college_type: "government",
    established_year: 1955,
    affiliation: "State University",
    naac_grade: "A++",
    nirf_rank: 10,
    total_intake: 1200,
    website: "http://www.jaduniv.edu.in",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/6/60/Jadavpur_University_Logo.svg/1200px-Jadavpur_University_Logo.svg.png",
    overview: "Jadavpur University offers world-class engineering education at highly subsidized fees, resulting in unmatched ROI.",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 10000, fees_per_year: 2500, degree_type: "UG", specialisation: "Computer Science", seats_available: 65 }],
    placements: [{ year: 2024, average_ctc: 16.0, median_ctc: 12.0, highest_ctc: 85.0, placement_percentage: 95, top_recruiters: "Atlassian, Amazon, TCS", total_offers: 900 }],
    cutoffs: [{ exam_name: "WBJEE", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 68, year: 2024, round: 2 }]
  },
  {
    name: "Indian Institute of Information Technology Hyderabad",
    location: "Hyderabad",
    state: "Telangana",
    rating: 4.8,
    college_type: "private",
    established_year: 1998,
    affiliation: "Deemed University",
    naac_grade: "A++",
    nirf_rank: 55,
    total_intake: 300,
    website: "https://www.iiit.ac.in",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e4/IIIT_Hyderabad_Logo.svg/1200px-IIIT_Hyderabad_Logo.svg.png",
    overview: "IIIT Hyderabad is synonymous with top-tier computer science research and boasts placements comparable to top IITs.",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 1400000, fees_per_year: 350000, degree_type: "UG", specialisation: "Computer Science", seats_available: 150 }],
    placements: [{ year: 2024, average_ctc: 32.2, median_ctc: 28.0, highest_ctc: 74.0, placement_percentage: 100, top_recruiters: "Google, Microsoft, Meta, Apple", total_offers: 300 }],
    cutoffs: [{ exam_name: "JEE Main", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 1687, year: 2024, round: 4 }]
  },
  {
    name: "Manipal Institute of Technology",
    location: "Manipal",
    state: "Karnataka",
    rating: 4.4,
    college_type: "private",
    established_year: 1957,
    affiliation: "Deemed University",
    naac_grade: "A++",
    nirf_rank: 61,
    total_intake: 2000,
    website: "https://manipal.edu/mit.html",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e4/Manipal_University_logo.png/220px-Manipal_University_logo.png",
    overview: "MIT Manipal is a leading private engineering institute famous for its vibrant campus life and strong alumni network (including Satya Nadella).",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 1800000, fees_per_year: 450000, degree_type: "UG", specialisation: "Computer Science", seats_available: 200 }],
    placements: [{ year: 2024, average_ctc: 12.5, median_ctc: 8.5, highest_ctc: 54.0, placement_percentage: 85, top_recruiters: "Microsoft, Amazon, TCS", total_offers: 1500 }],
    cutoffs: [{ exam_name: "MET", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 1083, year: 2024, round: 1 }]
  },
  {
    name: "Thapar Institute of Engineering and Technology",
    location: "Patiala",
    state: "Punjab",
    rating: 4.4,
    college_type: "private",
    established_year: 1956,
    affiliation: "Deemed University",
    naac_grade: "A+",
    nirf_rank: 20,
    total_intake: 1500,
    website: "https://www.thapar.edu",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/2/23/Thapar_Institute_of_Engineering_and_Technology_Logo.png/220px-Thapar_Institute_of_Engineering_and_Technology_Logo.png",
    overview: "TIET is a well-established private engineering institute in North India with strong academic programs and placements.",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 1900000, fees_per_year: 475000, degree_type: "UG", specialisation: "Computer Science", seats_available: 800 }],
    placements: [{ year: 2024, average_ctc: 11.9, median_ctc: 10.0, highest_ctc: 55.0, placement_percentage: 85, top_recruiters: "Amazon, JP Morgan, TCS", total_offers: 1200 }],
    cutoffs: [{ exam_name: "JEE Main", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 12000, year: 2024, round: 1 }]
  },
  {
    name: "Netaji Subhas University of Technology",
    location: "New Delhi",
    state: "Delhi",
    rating: 4.5,
    college_type: "government",
    established_year: 1983,
    affiliation: "State University",
    naac_grade: "A",
    nirf_rank: 60,
    total_intake: 1200,
    website: "http://www.nsut.ac.in",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Netaji_Subhas_University_of_Technology.svg/1200px-Netaji_Subhas_University_of_Technology.svg.png",
    overview: "Formerly NSIT, this university is highly preferred by Delhi students for its exceptional tech placements.",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 850000, fees_per_year: 212500, degree_type: "UG", specialisation: "Computer Science", seats_available: 180 }],
    placements: [{ year: 2024, average_ctc: 16.0, median_ctc: 12.0, highest_ctc: 62.0, placement_percentage: 85, top_recruiters: "Google, Microsoft, Amazon", total_offers: 1100 }],
    cutoffs: [{ exam_name: "JEE Main", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 3255, year: 2024, round: 5 }]
  },
  {
    name: "Motilal Nehru National Institute of Technology",
    location: "Prayagraj",
    state: "Uttar Pradesh",
    rating: 4.6,
    college_type: "government",
    established_year: 1961,
    affiliation: "Autonomous",
    naac_grade: "A",
    nirf_rank: 49,
    total_intake: 1000,
    website: "http://www.mnnit.ac.in",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/c/cd/MNNIT_Allahabad_Logo.png/220px-MNNIT_Allahabad_Logo.png",
    overview: "MNNIT Allahabad is famous for producing top-tier software engineers and has some of the best placement stats among NITs.",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 500000, fees_per_year: 125000, degree_type: "UG", specialisation: "Computer Science", seats_available: 172 }],
    placements: [{ year: 2024, average_ctc: 17.5, median_ctc: 14.0, highest_ctc: 82.0, placement_percentage: 90, top_recruiters: "Amazon, Oracle, Microsoft", total_offers: 850 }],
    cutoffs: [{ exam_name: "JEE Main", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 4295, year: 2024, round: 6 }]
  },
  {
    name: "RV College of Engineering",
    location: "Bengaluru",
    state: "Karnataka",
    rating: 4.4,
    college_type: "private",
    established_year: 1963,
    affiliation: "VTU",
    naac_grade: "B",
    nirf_rank: 96,
    total_intake: 1200,
    website: "https://www.rvce.edu.in",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4b/RV_College_of_Engineering_logo.png/220px-RV_College_of_Engineering_logo.png",
    overview: "RVCE is the top-ranked private engineering college in Karnataka, benefiting immensely from its location in India's IT capital.",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 1000000, fees_per_year: 250000, degree_type: "UG", specialisation: "Computer Science", seats_available: 120 }],
    placements: [{ year: 2024, average_ctc: 14.5, median_ctc: 10.0, highest_ctc: 62.0, placement_percentage: 90, top_recruiters: "Cisco, Amazon, Microsoft", total_offers: 1100 }],
    cutoffs: [{ exam_name: "KCET", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 242, year: 2024, round: 2 }]
  },
  {
    name: "Kalinga Institute of Industrial Technology",
    location: "Bhubaneswar",
    state: "Odisha",
    rating: 4.1,
    college_type: "deemed",
    established_year: 1992,
    affiliation: "Deemed University",
    naac_grade: "A++",
    nirf_rank: 39,
    total_intake: 3000,
    website: "https://kiit.ac.in",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/4/42/KIIT_logo.svg/1200px-KIIT_logo.svg.png",
    overview: "KIIT offers excellent infrastructure and consistently strong mass placements in the IT sector.",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 1400000, fees_per_year: 350000, degree_type: "UG", specialisation: "Computer Science", seats_available: 1500 }],
    placements: [{ year: 2024, average_ctc: 7.2, median_ctc: 6.0, highest_ctc: 63.0, placement_percentage: 85, top_recruiters: "HighRadius, TCS, Cognizant", total_offers: 4500 }],
    cutoffs: [{ exam_name: "KIITEE", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 5000, year: 2024, round: 1 }]
  },
  {
    name: "PEC University of Technology",
    location: "Chandigarh",
    state: "Chandigarh",
    rating: 4.3,
    college_type: "government",
    established_year: 1921,
    affiliation: "Deemed University",
    naac_grade: "B+",
    nirf_rank: 100,
    total_intake: 800,
    website: "https://pec.ac.in",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b3/Punjab_Engineering_College_logo.png/220px-Punjab_Engineering_College_logo.png",
    overview: "Punjab Engineering College (PEC) is a prestigious and historic engineering institution known for its strong alumni network.",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 700000, fees_per_year: 175000, degree_type: "UG", specialisation: "Computer Science", seats_available: 120 }],
    placements: [{ year: 2024, average_ctc: 13.5, median_ctc: 10.5, highest_ctc: 83.0, placement_percentage: 85, top_recruiters: "Microsoft, Amazon, Goldman Sachs", total_offers: 750 }],
    cutoffs: [{ exam_name: "JEE Main", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 10515, year: 2024, round: 6 }]
  },
  {
    name: "National Institute of Technology Warangal",
    location: "Warangal",
    state: "Telangana",
    rating: 4.6,
    college_type: "government",
    established_year: 1959,
    affiliation: "Autonomous",
    naac_grade: "A",
    nirf_rank: 21,
    total_intake: 900,
    website: "https://www.nitw.ac.in",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/2/23/NIT_Warangal_logo.png/220px-NIT_Warangal_logo.png",
    overview: "NIT Warangal is highly reputed for its excellent coding culture and top-notch placements in software engineering.",
    courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 Years", fees: 500000, fees_per_year: 125000, degree_type: "UG", specialisation: "Computer Science", seats_available: 135 }],
    placements: [{ year: 2024, average_ctc: 16.5, median_ctc: 13.0, highest_ctc: 88.0, placement_percentage: 90, top_recruiters: "Amazon, Oracle, Qualcomm", total_offers: 850 }],
    cutoffs: [{ exam_name: "JEE Main", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 2075, year: 2024, round: 6 }]
  },
  {
    name: "College of Engineering Pune",
    location: "Pune",
    state: "Maharashtra",
    rating: 4.5,
    college_type: "government",
    established_year: 1854,
    affiliation: "COEP Technological University",
    naac_grade: "A",
    nirf_rank: 73,
    total_intake: 900,
    website: "https://www.coep.org.in",
    image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/1/14/College_of_Engineering%2C_Pune_logo.png/220px-College_of_Engineering%2C_Pune_logo.png",
    overview: "COEP is one of the oldest and most prestigious engineering colleges in Asia, highly preferred by students in Maharashtra.",
    courses: [{ name: "B.Tech Computer Engineering", duration: "4 Years", fees: 400000, fees_per_year: 100000, degree_type: "UG", specialisation: "Computer Science", seats_available: 120 }],
    placements: [{ year: 2024, average_ctc: 11.2, median_ctc: 9.0, highest_ctc: 50.0, placement_percentage: 85, top_recruiters: "Credit Suisse, Bajaj, TCS", total_offers: 750 }],
    cutoffs: [{ exam_name: "MHT CET", course_name: "CSE", category: "General", opening_rank: 1, closing_rank: 150, year: 2024, round: 2 }]
  }
];

async function seed() {
  await sequelize.sync();
  for (const c of top20Colleges) {
    await College.destroy({ where: { name: c.name } });
    const college = await College.create(c);
    
    for (const crs of c.courses) {
      await Course.create({ ...crs, college_id: college.id });
    }
    for (const pl of c.placements) {
      await Placement.create({ ...pl, college_id: college.id });
    }
    for (const cut of c.cutoffs) {
      await Cutoff.create({ ...cut, college_id: college.id });
    }
  }
  console.log("Top 20 colleges fully seeded!");
  process.exit(0);
}

seed();
